# Generated by Django 4.1.4 on 2023-01-04 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
